# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: mtm-be-new

frameworkVersion: "3"
	
useDotenv: true

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  apiGateway:
    binaryMediaTypes:
            - '*/*'

# The `functions` block defines what code to deploy
functions:
  global:
    handler: netlify/functions/api.handler
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: /{proxy+}
          method: ANY
