export const {
  APP_ACCESS_TOKEN,
  PORT: appPort,
  STORE_NAME,
  JWT_SECRET,
  ADMIN_PASSWORD,
  MEASUREMENT_ITEM_OVERSIZE,
  SPF_IMG_BASE_URL,
  GORGIAS_BASE_URL,
  GORGIAS_AUTHORIZATION_KEY,
} = process.env;
